apiVersion: v1
kind: Service
metadata:
  name: casino-db
  labels:
    app: casino-db
spec:
  # ClusterIP: http://casino-db:5432
  type: ClusterIP
  selector:
    app: casino-db
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
